### ISSUE TITLE
Zoom bar stacks underneath image

### ISSUE THREAD

**Issue by nicolettehayes** [stamen/gcpi#10]
the zoom bar displays underneath the image instead of next to it

![screen shot 2017-03-14 at 5 56 19 pm](https://cloud.githubusercontent.com/assets/12550451/23928873/9afaba16-08df-11e7-879e-16674d754c77.png)

![gcpi](https://cloud.githubusercontent.com/assets/12550451/23928899/c6a09906-08df-11e7-80e1-de24fac48ff4.gif)

**Comment by sconnelley** [comment]
yes weird, client mentioned that as well.  But good news we are removing the zoom bar in favor of touch / trackpad scrolling.  Although maybe we should add zoom buttons to image panel to keep consistency with the map side of things.

**Comment by sconnelley** [comment]
removed zoom slider, added scrollwheel and double click zooming
