### ISSUE TITLE
scroll cut off

### ISSUE THREAD

**Issue by nicolettehayes** [stamen/gcpi#13]
Having played with the interface a little, it feels like having the "load images" feature be always accessible would be useful. However, I know the client requested the maximum possible space for seeing the images, so what if we put the two load-filetypes side by side, and above the scroll fold?

So this (status bar and new photo/file options) would always be visible no matter how far down you scroll:
![screen shot 2017-03-14 at 6 24 05 pm](https://cloud.githubusercontent.com/assets/12550451/23929466/9fbb3018-08e3-11e7-9ef0-cc8861fdaff0.png)

**Comment by sconnelley** [comment]
@nicolettehayes -- I like where your going with that idea.  What if we did something like this very crude image I made?
![image](https://cloud.githubusercontent.com/assets/565486/24015186/1046496e-0a5e-11e7-8af2-5fb9ceff3b4b.png)

The main idea is to make the image and map the same size. The Control Points and upload targets shouldn't be that big either...
