### ISSUE TITLE
Checkmark functioning

### ISSUE THREAD

**Issue by nicolettehayes** [stamen/gcpi#9]
The checkmark should indicate when you're done dragging the point around. Drag, click checkmark, checkmark disappears and point turns green.

Currently I can't figure out how to "set" a point (i.e. make it go from yellow to green in the lefthand bar, and make the checkmark go away).

Additionally, re-clicking on a set point on the map should make the check mark reappear until clicked.

**Comment by sconnelley** [comment]
Moved away from checkmark idea to having a tooltip next to the marker with allowable actions.

Green markers indicate markers belonging to current image. Grey markers are default state.
![image](https://cloud.githubusercontent.com/assets/565486/24180778/50bef3f0-0e8d-11e7-9566-95b21ef9b6fb.png)

Yellow markers indicate selected marker (notice tooltip with actions)
![image](https://cloud.githubusercontent.com/assets/565486/24180814/8106388e-0e8d-11e7-8b09-1ffa8bc51c80.png)
